name: Build OnlyOffice Packages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get version from Dockerfile
      run: |
        PRODUCT_VERSION=$(cat Dockerfile | grep PRODUCT_VERSION | sed -e 's|[^=]*=\(\S*\).*|\1|')
        BUILD_NUMBER=$(cat Dockerfile | grep BUILD_NUMBER | sed -e 's|[^=]*=*||')
        echo "PRODUCT_VERSION=$PRODUCT_VERSION" >> $GITHUB_ENV
        echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV
        echo "TARGET_VER=${PRODUCT_VERSION}-${BUILD_NUMBER}" >> $GITHUB_ENV
    - name: Build the Builder Docker image
      run: docker build . --file Dockerfile --tag onlyoffice-builder
    - name: Build Only Office
      run: docker run --rm -v $PWD:/build/out/ --env PRODUCT_VERSION=${{ env.PRODUCT_VERSION }} --env BUILD_NUMBER=${{ env.BUILD_NUMBER }} onlyoffice-builder build.sh
    - name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.TARGET_VER }}
        release_name: ${{ env.TARGET_VER }}
        draft: true
        prerelease: false
    - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./onlyoffice-documentserver_${{ env.TARGET_VER }}_amd64.deb
        asset_name: onlyoffice-documentserver_${{ env.TARGET_VER }}_amd64.deb
        asset_content_type: application/octet-stream
    - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./onlyoffice-documentserver-${{ env.TARGET_VER }}.x86_64.rpm
        asset_name: onlyoffice-documentserver-${{ env.TARGET_VER }}.x86_64.rpm
        asset_content_type: application/octet-stream
    - uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}
